// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

const manifest = {
  routes: {},
  islands: {},
  baseUrl: import.meta.url,
};

export default manifest;
